import C from './lib/circle';
import L from './lib/line';
import P from './lib/pie';
import B from './lib/bar';
import * as D from './lib/defaults';
export { version } from './lib/util';
export const Circle = C;
export const Line = L;
export const Pie = P;
export const Bar = B;
export const defaults = D;
